### PR TITLE
fixed path collision for path patch

### LINKED ISSUE #212: One can introduce duplicate paths
Reported way of reproduction:
1. Create two routes for the same uri, with different hosts.
2. Update one of the routes to have the same hosts.

It shouldn't be possible to update the path hosts when it generates a conflict.

### PR DESCRIPTION
**Pull request by NorthFury**
fixes #212

### CODE REVIEW

File: src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala [hunk 1]
```diff
@@ -165,6 +165,23 @@ class PatchPathsSpec extends FunSpec with BeforeAndAfter with Matchers {
         }
       }
 
+      describe("when path patch updates host ids so that a path collision exists") {
+        it("should return the 400 Bad Request status") {
```
Comment (mo-gr) [inline src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala]: There is also `409 Conflict` Seems more appropriate, don't you think?

File: src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala [hunk 2]
```diff
@@ -165,6 +165,23 @@ class PatchPathsSpec extends FunSpec with BeforeAndAfter with Matchers {
...
+
+          PathsRepoHelper.insertPath(samplePath(uri = uri, hostIds = Seq(1L, 2L)))
+          val secondPath = PathsRepoHelper.insertPath(samplePath(uri = uri, hostIds = Seq(3L, 4L)))
+
+          val secondPathId = secondPath.id.getOrElse(-1L)
+
+          val response = PathsSpecsHelper.patchSlashPaths(secondPathId, pathPatchHostIdsJsonString(Seq(2L)), token)
+
+          response.status should be(StatusCodes.BadRequest)
+          entityString(response).parseJson.convertTo[Error].errorType should be("IPP")
```
Comment (mo-gr) [inline src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala]: What is IPP?

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala [hunk 3]
```diff
@@ -76,38 +76,67 @@ class PathsPostgresRepo @Inject() (
...
+  }
 
-    db.run {
-      query.result
-    }.map{ existingPathHostIds =>
-      val pathWithAllHostIdsExists = existingPathHostIds.exists(_.isEmpty)
-      val hostIdsIntersectWithExistingPathHostIds = existingPathHostIds.flatten
-        .intersect(path.hostIds)
-        .nonEmpty
+  private def hostIdCollisionExists(newHostIds: Seq[Long], existingPathHostIds: scala.collection.Seq[Seq[Long]]) = {
```
Comment (mo-gr) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: A `Seq[Seq[Long]]`? Can't it be flattened?

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala [hunk 4]
```diff
@@ -76,38 +76,67 @@ class PathsPostgresRepo @Inject() (
...
+    }.map{ existingPathHostIds =>
+      hostIdCollisionExists(path.hostIds, existingPathHostIds)
+    }
+  }
+
+  override def collisionExistsForPatch(pathId: Long, newHostIds: Seq[Long]): Future[Boolean] = {
+    logger.debug("path uri collision check")
+
+    selectById(pathId).flatMap {
+      case None => Future(true)
```
Comment (mo-gr) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: If we can't select the path by Id, we return `true`, meaning a collision exists? I don't understand that. Seems wrong to me

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala [hunk 5]
```diff
@@ -76,38 +76,67 @@ class PathsPostgresRepo @Inject() (
...
+      .map(_.hostIds)
+
+    db.run {
+      query.result
+    }.map{ existingPathHostIds =>
+      hostIdCollisionExists(path.hostIds, existingPathHostIds)
+    }
+  }
+
+  override def collisionExistsForPatch(pathId: Long, newHostIds: Seq[Long]): Future[Boolean] = {
```
Comment (mo-gr) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: The existence of a method named `collisionExistsForPath` AND a method named `collisionExistsForPatch`, that operates on paths confuses the hell out of me. Also, I don't think `patch` is a word that should be used on this level. On the Postgres level, it is more like `collisionExistsForUpdate`, isn't it?

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala [hunk 6]
```diff
@@ -76,38 +76,67 @@ class PathsPostgresRepo @Inject() (
...
 
-    val query = Paths
-      .filter { pathRow =>
-        val pathHasStar: Rep[Boolean] = path.hasStar.contains(true)
+  private def filterPathsWithUriCollision(pathUri: String, pathHasStar: Boolean)(pathRow: PathsTable) = {
+    import SlickExtension.startsWith
 
-        val starPathConflictsWithExistingPath = pathHasStar && startsWith(path.uri, pathRow.uri)
-        val existingStarPathConflictsWithPath = pathRow.hasStar && startsWith(pathRow.uri, path.uri)
+    val pathHasStarCondition: Rep[Boolean] = pathHasStar
```
Comment (mo-gr) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: What's happening here? Implicit conversion from `Boolean` to `Rep[Boolean]`?

File: src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala (hunk 2 above)
Comment (NorthFury) [inline src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala]: There are 3 letter codes for each Rejection. `IPP` is `InvalidPathPatch`.

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala (hunk 4 above)
Comment (NorthFury) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: good catch

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala (hunk 3 above)
Comment (NorthFury) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: It can't be flattened because of the following line. Business logic requires this structure.

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala (hunk 5 above)
Comment (NorthFury) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: `collisionExistsForUpdate` is a way better name :+1:

File: src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala (hunk 6 above)
Comment (NorthFury) [inline src/main/scala/org/zalando/spearheads/innkeeper/dao/PathsPostgresRepo.scala]: This is a forced implicit conversion. Having this inlined results in code that doesn't compile anymore.

File: src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala (hunk 1 above)
Comment (NorthFury) [inline src/it/scala/org/zalando/spearheads/innkeeper/routes/PatchPathsSpec.scala]: A really valid point that points to something more concerning. The response doesn't give enough information back pertaining to why it wasn't a successful request. I'll add this change.

**Comment by mo-gr** [comment]
:+1:
